"""Initial Migration

Revision ID: 09c4facd0c10
Revises: e22a92fb75e1
Create Date: 2019-10-02 14:58:48.223346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09c4facd0c10'
down_revision = 'e22a92fb75e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('writers', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column('writers', sa.Column('profile_pic_path', sa.String(), nullable=True))
    op.drop_column('writers', 'password_secure')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('writers', sa.Column('password_secure', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('writers', 'profile_pic_path')
    op.drop_column('writers', 'password_hash')
    # ### end Alembic commands ###
