"""Initial Migration

Revision ID: 742b46e64bc9
Revises: 72c503070557
Create Date: 2019-10-03 11:27:30.958088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '742b46e64bc9'
down_revision = '72c503070557'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscribers')
    # ### end Alembic commands ###
